version: '3'
services:
  webserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
